import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import "./globals.css";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import theme from "@/utils/theme";
import { Notifications } from '@mantine/notifications';
import '@mantine/notifications/styles.css';
import { SessionProvider } from "next-auth/react";

const inter = Inter({
  variable: "--font-inter",
  weight: "variable",
  display: "swap",
  preload: true,
  fallback: ["system-ui", "sans-serif"],
  subsets: ["latin-ext", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string; }>
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang="pt-BR">
      <body
        className={`${inter.variable} antialiased`}
      >
        <SessionProvider>
          <NextIntlClientProvider>
            <MantineProvider defaultColorScheme="light" theme={theme}>
              <Notifications className="!z-[2000]"/>
              {children}
            </MantineProvider>
          </NextIntlClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
